---
abstract: ~
author:
  - 'Gabor Szabo'
build_requires:
  ExtUtils::MakeMaker: 6.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.01'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Task-Test
no_index:
  directory:
    - inc
    - t
requires:
  Test::Exception: 0.27
  Test::MockObject: 1.09
  Test::More: 0.88
  Test::Most: 0
  Test::NoWarnings: 0.084
  Test::Output: 0
  Test::Perl::Critic: 1.02
  Test::Pod: 1.45
  Test::Pod::Coverage: 1.08
  Test::Script: 1.07
  Test::WWW::Mechanize: 0
  perl: 5.008005
resources:
  bugtracker: https://github.com/szabgab/Task-Test
  homepage: https://github.com/szabgab/Task-Test
  license: http://dev.perl.org/licenses/
  repository: https://github.com/szabgab/Task-Test
version: 0.01
